apiVersion: v2
name: bitbucket
description: A chart for installing Bitbucket Data Center on Kubernetes
type: application
version: 1.10.17
appVersion: 7.21.11
kubeVersion: ">=1.21.x-0"
keywords:
- Bitbucket
- Bitbucket Server
- Bitbucket Data Center
- Bitbucket DC
- Atlassian
home: https://atlassian.github.io/data-center-helm-charts/
icon: https://atlassian.github.io/data-center-helm-charts/icons/bitbucket.svg
sources:
- https://github.com/atlassian/data-center-helm-charts
- https://bitbucket.org/atlassian-docker/docker-atlassian-bitbucket-server/
deprecated: false
annotations:
  artifacthub.io/containsSecurityUpdates: "false"
  artifacthub.io/changes: |-
    - "Update appVersion in DC apps"
    - "Fix bitbucket helmfile to optimize memory usage"
    - "Update bitbucket templates to update dependencies"
    - "Remove bitbucket values to optimize memory usage"
    - "Update bitbucket tests to update dependencies"

dependencies:
- name: common
  version: 1.0.0
  repository: https://atlassian.github.io/data-center-helm-charts
